spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_db;DB_CLOSE_DELAY=-1
    
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql
    
  batch:
    job:
      enabled: false  
batch:
  executor:
    corePoolSize: 5
    maxPoolSize: 10