spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_db;DB_CLOSE_DELAY=-1
    
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.sql
  
scheduler:
  threadPoolSize: 10
  pollingIntervalMins: 5
  lockAtleastForSecs: 60
  lockAtmostForSecs: 60