
resilience:
  circuitBreakers:
    default:
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      permittedNumberOfCallsInHalfOpenState: 10
      maxWaitDurationInHalfOpenState: 60000
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      minimumNumberOfCalls: 100
      waitDurationInOpenState: 60000
      automaticTransitionFromOpenToHalfOpenEnabled: false
      metricsEnabled: true

management:
  metrics:
    export:
      atlas:
        # The location of your Atlas server
        uri: http://localhost:7101/api/v1/publish
        # You will probably want to conditionally disable Atlas publishing in local development.
        enabled: true
        # The interval at which metrics are sent to Atlas. The default is 1 minute.
        step: 10s