
resilience:
  circuitBreaker:
    default:
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      permittedNumberOfCallsInHalfOpenState: 10
      maxWaitDurationInHalfOpenState: 60000
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 100
      minimumNumberOfCalls: 100
      waitDurationInOpenState: 60000
      # recordExceptions: java.io.IOException, java.util.concurrent.TimeoutExceotion
      # ignoreExceptions: com.example.BusinessException
      automaticTransitionFromOpenToHalfOpenEnabled: false
      metricsEnabled: false
    CB-Fail:
      slidingWindowSize: 2
      minimumNumberOfCalls: 2

  retry:
    default:
      maxAttempts: 3
      waitDuration: 500
      #retryExceptions: java.io.IOException, java.util.concurrent.TimeoutExceotion
      #ignoreExceptions: com.example.BusinessException
      failAfterMaxAttempts: true 
